// <auto-generated />
namespace CharacterThrowdown.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Battles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Battles));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041637324_Battles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
