// <auto-generated />
namespace CharacterThrowdown.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update5));
        
        string IMigrationMetadata.Id
        {
            get { return "201811301506404_Update5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
